version: '3.1'

services:

  app:
    container_name: app
    image: app
    build:
      context: ../
      dockerfile: ./app/Dockerfile
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
